from collections import OrderedDict
from dataclasses import dataclass
from typing import Any, Mapping, cast

import numpy as np
import numpy.typing as npt
import pandas as pd
from relbench.base import TaskType
from scipy.special import softmax

from relicl.trace import load_trace
from relicl.typing import EvalMode

# Run-level metadata, constant across all rows of one predictions file.
META_COLUMNS = ["name", "id", "eval_mode"]

# Per-row columns written for every task type, and the ones only classification has.
VALUE_COLUMNS = ["key", "cutoff_timestamp", "y_true", "y_pred", "task_type"]
CLASSIFICATION_COLUMNS = ["p_pred", "proba"]


@dataclass
class Predictions:
    """Collects all predictions for a particular task"""

    task_name: str
    id: str
    eval_mode: EvalMode
    df: pd.DataFrame

    @property
    def is_regression(self) -> bool:
        return self.df.loc[0, "task_type"] == TaskType.REGRESSION.value

    @staticmethod
    def load(filename) -> "Predictions":
        """Loads a predictions file generated by RelICL"""

        # Runs written before predictions moved to parquet.
        if filename.endswith(".yaml"):
            return Predictions._load_legacy_yaml(filename)

        df = pd.read_parquet(filename)
        is_regression = df.loc[0, "task_type"] == TaskType.REGRESSION.value
        value_columns = (
            VALUE_COLUMNS if is_regression else VALUE_COLUMNS + CLASSIFICATION_COLUMNS
        )
        assert list(df.columns) == META_COLUMNS + value_columns

        return Predictions._from_frame(df, value_columns)

    @staticmethod
    def _from_frame(df: pd.DataFrame, value_columns: list[str]) -> "Predictions":
        """Splits a loaded frame into run-level metadata and per-row values."""

        task_name = cast(str, df.loc[0, "name"])
        _id = cast(str, df.loc[0, "id"])
        eval_mode = EvalMode(cast(str, df.loc[0, "eval_mode"]))
        assert all(df["name"] == task_name)
        assert all(df["id"] == _id)
        assert all(df["eval_mode"] == eval_mode)

        return Predictions(task_name, _id, eval_mode, df[value_columns])

    @staticmethod
    def _load_legacy_yaml(filename: str) -> "Predictions":
        """Loads the pre-parquet YAML trace format (one flow mapping per line)."""

        df = pd.DataFrame.from_records(load_trace(filename))
        is_regression = df.loc[0, "task_type"] == TaskType.REGRESSION.value
        value_columns = (
            VALUE_COLUMNS if is_regression else VALUE_COLUMNS + CLASSIFICATION_COLUMNS
        )
        # The trace format carried "time_ns" and "event", which parquet files do not,
        # and ordered the value columns differently.
        expected_columns = [
            "name",
            "id",
            "time_ns",
            "event",
            "eval_mode",
            "cutoff_timestamp",
            "key",
            "y_true",
            "y_pred",
            "task_type",
        ]
        if not is_regression:
            expected_columns += CLASSIFICATION_COLUMNS
        assert list(df.columns) == expected_columns
        assert all(df["event"] == "prediction")

        return Predictions._from_frame(df, value_columns)

    def save(self, filename) -> None:
        """Writes all predictions of one split as a single parquet file."""

        n = len(self.df)
        value_columns = (
            VALUE_COLUMNS
            if self.is_regression
            else VALUE_COLUMNS + CLASSIFICATION_COLUMNS
        )

        # Metadata is constant per file; parquet dictionary-encodes it away.
        df = pd.DataFrame(
            dict(
                name=np.full(n, self.task_name),
                id=np.full(n, self.id),
                eval_mode=np.full(n, str(self.eval_mode)),
            )
        )
        for column in value_columns:
            df[column] = self.df[column].to_numpy()

        df.to_parquet(filename, index=False)


def ensemble_proba(
    probas: list[npt.NDArray], average_logits: bool = True
) -> npt.NDArray:
    if average_logits:
        # TODO: No overload variant of "stack" matches argument
        #  types "ndarray[tuple[Any, ...], dtype[Any]]", "int"
        out = np.stack(np.log(probas), axis=0)  # type: ignore
        return cast(npt.NDArray, softmax(out.mean(axis=0), axis=1))
    else:
        out = np.stack(probas, axis=0)
        return out.mean(axis=0)


def _join_preds(preds: list[Predictions]) -> pd.DataFrame:
    # join all predictions together
    assert _all_equal([len(pred.df) for pred in preds])
    n = len(preds[0].df)
    df: pd.DataFrame | None = None
    for i, pred in enumerate(preds):
        renamed_df = pred.df.add_suffix(f"_{i}")

        if df is None:
            df = renamed_df
        else:
            df = df.merge(
                renamed_df,
                left_on=["key_0", "cutoff_timestamp_0"],
                right_on=[f"key_{i}", f"cutoff_timestamp_{i}"],
                how="inner",
            )
            # noinspection PyTypeChecker
            assert len(df) == n
            assert all(df["y_true_0"] == df[f"y_true_{i}"])

    assert df is not None, "no predictions to join"
    return df


def ensemble_predictions(preds: list[Predictions], average_logits=True) -> Predictions:
    assert _all_equal([pred.task_name for pred in preds])
    assert _all_equal([pred.eval_mode for pred in preds])
    assert _all_equal([len(pred.df) for pred in preds])
    assert _all_equal([pred.is_regression for pred in preds])
    n_preds, task_name, eval_mode, n = (
        len(preds),
        preds[0].task_name,
        preds[0].eval_mode,
        len(preds[0].df),
    )

    # join it
    df = _join_preds(preds)

    # now compute the result
    def all_columns(prefix: str):
        return [f"{prefix}_{i}" for i in range(n_preds)]

    if preds[0].is_regression:
        y_pred = np.mean([df[c].to_numpy() for c in all_columns("y_pred")], axis=0)
        result_df = pd.DataFrame(
            dict(
                key=df["key_0"],
                cutoff_timestamp=df["cutoff_timestamp_0"],
                y_true=df["y_true_0"],
                y_pred=y_pred,
                task_type=df["task_type_0"],
            )
        )
    else:
        proba = ensemble_proba(
            [np.stack(df[c], axis=0) for c in all_columns("proba")],
            average_logits=average_logits,
        )
        assert np.isclose(proba.sum(axis=1), 1).all()
        y_pred = np.argmax(proba, axis=1)
        p_pred = np.max(proba, axis=1)
        result_df = pd.DataFrame(
            dict(
                key=df["key_0"],
                cutoff_timestamp=df["cutoff_timestamp_0"],
                y_true=df["y_true_0"],
                y_pred=y_pred,
                task_type=df["task_type_0"],
                p_pred=p_pred,
                proba=[proba[i, :] for i in range(n)],
            )
        )

    result_id = (
        f"ensemble([{','.join([pred.id for pred in preds])}]"
        f",average_logits={average_logits})"
    )
    return Predictions(task_name, result_id, eval_mode, result_df)


def _all_equal(l):
    return all([x == l[0] for x in l])


def diff_pred(preds: list[Predictions]) -> dict[str, list[Any]]:
    n_preds = len(preds)
    task_names = [pred.task_name for pred in preds]
    eval_modes = [pred.eval_mode for pred in preds]
    ids = [pred.id for pred in preds]
    n = [len(pred.df) for pred in preds]
    result: dict[str, list[Any]] = {}
    if not _all_equal(task_names):
        result["task_name"] = task_names
    if not _all_equal(eval_modes):
        result["eval_mode"] = eval_modes
    result["id"] = ids
    if not _all_equal(n):
        result["n"] = n
    if len(result) > 1:
        return result

    is_regression = preds[0].is_regression
    if not _all_equal([pred.is_regression for pred in preds]):
        result["is_regression"] = [pred.is_regression for pred in preds]
        return result

    # now diff the actual predictions
    def all_columns(prefix: str) -> list[str]:
        return [f"{prefix}_{j}" for j in range(n_preds)]

    pred_diff: list[Mapping[str, Any]] = []
    df = _join_preds(preds)
    for i in range(n[0]):
        # TODO: Invalid index type "tuple[int, list[str]]" for "_LocIndexerFrame[DataFrame]"
        y_preds: list[str, Any] = df.loc[i, all_columns("y_pred")].tolist()  # type: ignore
        if not _all_equal(y_preds):
            row = OrderedDict(
                key=df.loc[i, "key_0"],
                cutoff_timestamp=df.loc[i, "cutoff_timestamp_0"],
                y_true=df.loc[i, "y_true_0"],
                y_preds=y_preds,
            )
            if not is_regression:
                # TODO: Value of type "..." is not indexable
                row["p_1"] = [df.loc[i, c][1] for c in all_columns("proba")]  # type: ignore
            pred_diff.append(row)
    if len(pred_diff) > 0:
        result["predictions"] = pred_diff

    return result
