import json
import os
from pathlib import Path

import numpy as np
import pandas as pd

# RelICL requires the task id column to be named this and to come first.
TASK_ID_COL = "__task_id"

# Generated LaTeX tables land here.
PAPER_GENERATED = Path(__file__).resolve().parents[2] / "paper" / "tex" / "generated"


# Settings. ############################################################################


def env_int(name: str, default: int) -> int:
    """An integer setting that an environment variable may override."""
    return int(os.environ.get(name, str(default)))


def env_flag(name: str) -> bool:
    """A setting that is on iff the environment variable is 1."""
    return os.environ.get(name, "0") == "1"


# Data. ################################################################################


def balanced_labels(rng: np.random.Generator, n: int) -> np.ndarray:
    """Half ones, half zeros, shuffled."""
    labels = np.array([1] * (n // 2) + [0] * (n - n // 2), dtype=np.int64)
    rng.shuffle(labels)
    return labels


# Results. #############################################################################


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {path}")


def load_results(results_dir: Path) -> pd.DataFrame:
    """All per-run results of one example, one row per run."""
    rows = [json.loads(p.read_text()) for p in sorted(results_dir.glob("*.json"))]
    df = pd.DataFrame(rows)

    # Sanity check: Result files from before seeds were added would be averaged in.
    assert "seed" in df.columns and df["seed"].notna().all(), (
        "Remove result files without a seed from results/."
    )
    return df


def latex_cell(mean: float, sem: float, bold: bool, digits: int = 2) -> str:
    """Mean over seeds, with the SEM when there is more than one seed."""
    text = f"\\textbf{{{mean:.{digits}f}}}" if bold else f"{mean:.{digits}f}"
    return text if pd.isna(sem) else f"{text} $\\pm$ {sem:.{digits}f}"


def latex_header(module: str) -> str:
    return f"% Generated by `poetry run python -m {module}`. Do not edit."


def latex_auroc_table(
    module: str, summary: pd.DataFrame, digits: int = 2, bold: bool = True
) -> str:
    """One row per method with mean and SEM over seeds, optionally bolding the best."""
    lines = [
        latex_header(module),
        "\\begin{tabular}{lr}",
        "\\toprule",
        "\\textbf{Method} & \\textbf{AUROC} \\\\",
        "\\midrule",
    ]
    # Bold by the printed value, so that means that print alike are bolded alike.
    means = summary["mean"].round(digits)
    for method, mean, sem in zip(summary.index, means, summary["sem"]):
        cell = latex_cell(mean, sem, bold and mean == means.max(), digits)
        lines.append(f"{method} & {cell} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)
